using System;

namespace CarboLifeAPI.Data
{
    /// <summary>
    /// Where a CarboGroup came from.
    /// Reinforcement, SteelConnection and TimberConnection are the generated ones: they are rebuilt
    /// from the import settings on every run, so they must never be pruned, reinforced or given a
    /// connection allowance the way a group holding real elements is. See CarboGroup.IsAutoGenerated.
    /// Other is deliberately 0, so a group read from a file written before this existed can be
    /// recognised as unclassified and upgraded, see CarboGroup.UpgradeOriginFromLegacyFlags.
    /// </summary>
    [Serializable]
    public enum CarboGroupOrigin
    {
        /// <summary>Unclassified, the default for groups read from a pre 2.0 file.</summary>
        Other = 0,
        /// <summary>Made by the user in the app.</summary>
        Manual = 1,
        /// <summary>Built from imported elements.</summary>
        Import = 2,
        /// <summary>Generated reinforcement allowance.</summary>
        Reinforcement = 3,
        /// <summary>Generated steel connection allowance.</summary>
        SteelConnection = 4,
        /// <summary>Generated timber connection allowance.</summary>
        TimberConnection = 5
    }

    /// <summary>
    /// The categories the generators give their groups and elements. They are written into the
    /// project file, so they are fixed text rather than something derived from the origin, and they
    /// are collected here so the generators and the graph collectors cannot drift apart.
    /// </summary>
    public static class CarboGroupCategories
    {
        public const string Reinforcement = "Reinforcement";
        public const string SteelConnections = "Steel Connections";
        public const string TimberConnections = "Timber Connections";

        /// <summary>
        /// True when the category belongs to a generated allowance. An allowance is carbon that
        /// belongs to the element it was worked out from, so the graphs that merge by category
        /// report it against that element rather than as a category of its own.
        /// </summary>
        public static bool IsGeneratedAllowance(string category)
        {
            return category == Reinforcement
                || category == SteelConnections
                || category == TimberConnections;
        }
    }
}
